site_name: KampHack
nav:
  - Home: /#
  - Tickets: /#tickets
  - FAQ: /#faq
  - Wiki: https://md.warpzone.ms/s/wiki-kamphack
  - CfP: https://pretalx.c3voc.de/kamphack-2024/cfp
theme:
  name: null
  custom_dir: 'custom_theme/'
plugins: []