site_name: KampHack
nav:
  - Home: /#
  - Tickets: /#tickets
  - FAQ: /#faq
  - Wiki: https://md.warpzone.ms/s/wiki-kamphack
  - Fahrplan: https://pretalx.c3voc.de/kamphack-2024/schedule/
  - Engelsystem: https://md.warpzone.ms/kamphack24_engelsystem
theme:
  name: null
  custom_dir: 'custom_theme/'
plugins: []